In [1]:
import pandas as pd

train = pd.read_csv("dataset/Train_df.csv")

In [2]:
train.sample(5)

,Image_ID,class,confidence,ymin,xmin,ymax,xmax,class_id,ImagePath
4867,ID_EwVt2A.jpg,cssvd,1.0,53.0,0.0,1080.0,584.0,1,dataset/images/train/ID_EwVt2A.jpg
4317,ID_UQU7R6.jpg,cssvd,1.0,0.0,0.0,1080.0,810.0,1,dataset/images/train/ID_UQU7R6.jpg
4900,ID_k9u0Al.jpg,cssvd,1.0,119.0,210.0,478.0,778.0,1,dataset/images/train/ID_k9u0Al.jpg
613,ID_Wwb3Id.jpg,healthy,1.0,2148.0,786.0,3264.0,1654.0,2,dataset/images/train/ID_Wwb3Id.jpg
2669,ID_LMGLHb.jpg,anthracnose,1.0,3.0,68.0,559.0,556.0,0,dataset/images/train/ID_LMGLHb.jpg

In [3]:
category_ids = train["class"].unique()
category_ids = {n: i for i, n in enumerate(sorted(category_ids))}

category_ids

{'anthracnose': 0, 'cssvd': 1, 'healthy': 2}

In [4]:
train.apply(
	lambda x: [x["xmin"], x["ymin"], x["xmax"] - x["xmin"], x["ymax"] - x["ymin"]], axis=1
)

0            [15.0, 75.0, 180.0, 87.0]
1             [1.0, 58.0, 170.0, 75.0]
2           [29.0, 42.0, 320.0, 335.0]
3         [124.0, 112.0, 217.0, 292.0]
4         [259.0, 148.0, 153.0, 265.0]
                     ...
7825     [0.0, 3001.0, 3024.0, 1031.0]
7826      [0.0, 184.0, 2199.0, 3764.0]
7827     [360.0, 18.0, 1970.0, 1782.0]
7828    [174.0, 736.0, 3858.0, 1955.0]
7829    [1248.0, 57.0, 1075.0, 2678.0]
Length: 7830, dtype: object

In [5]:
train["category_id"] = train["class"].map(category_ids)
train["id"] = train.index.values
train["bbox"] = train.apply(
	lambda x: [x["xmin"], x["ymin"], x["xmax"] - x["xmin"], x["ymax"] - x["ymin"]], axis=1
)
train["image_id"] = train["ImagePath"].values


train.sample(5)

,Image_ID,class,confidence,ymin,xmin,ymax,xmax,class_id,ImagePath,category_id,id,bbox,image_id
5413,ID_uMzWDE.jpg,cssvd,1.0,381.0,313.0,1393.0,892.0,1,dataset/images/train/ID_uMzWDE.jpg,1,5413,"[313.0, 381.0, 579.0, 1012.0]",dataset/images/train/ID_uMzWDE.jpg
7363,ID_gxRGdX.jpeg,healthy,1.0,1317.0,1741.0,3024.0,3604.0,2,dataset/images/train/ID_gxRGdX.jpeg,2,7363,"[1741.0, 1317.0, 1863.0, 1707.0]",dataset/images/train/ID_gxRGdX.jpeg
5113,ID_koBtxN.jpg,cssvd,1.0,618.0,179.0,1256.0,1466.0,1,dataset/images/train/ID_koBtxN.jpg,1,5113,"[179.0, 618.0, 1287.0, 638.0]",dataset/images/train/ID_koBtxN.jpg
4839,ID_Bi4YAL.jpg,cssvd,1.0,293.0,734.0,694.0,1080.0,1,dataset/images/train/ID_Bi4YAL.jpg,1,4839,"[734.0, 293.0, 346.0, 401.0]",dataset/images/train/ID_Bi4YAL.jpg
1409,ID_MBpPL3.jpg,healthy,1.0,142.0,13.0,329.0,187.0,2,dataset/images/train/ID_MBpPL3.jpg,2,1409,"[13.0, 142.0, 174.0, 187.0]",dataset/images/train/ID_MBpPL3.jpg

In [7]:
train.sample(5)

,Image_ID,class,confidence,ymin,xmin,ymax,xmax,class_id,ImagePath,category_id,id,bbox,image_id
5999,ID_CdDyIi.jpg,cssvd,1.0,24.0,143.0,1280.0,857.0,1,dataset/images/train/ID_CdDyIi.jpg,1,5999,"[143.0, 24.0, 714.0, 1256.0]",dataset/images/train/ID_CdDyIi.jpg
4090,ID_VRSBDq.jpg,anthracnose,1.0,0.0,708.0,1520.0,1909.0,0,dataset/images/train/ID_VRSBDq.jpg,0,4090,"[708.0, 0.0, 1201.0, 1520.0]",dataset/images/train/ID_VRSBDq.jpg
4518,ID_hILuJg.jpg,cssvd,1.0,38.0,0.0,950.0,495.0,1,dataset/images/train/ID_hILuJg.jpg,1,4518,"[0.0, 38.0, 495.0, 912.0]",dataset/images/train/ID_hILuJg.jpg
5739,ID_PUwSfb.jpg,cssvd,1.0,710.0,623.0,1303.0,1044.0,1,dataset/images/train/ID_PUwSfb.jpg,1,5739,"[623.0, 710.0, 421.0, 593.0]",dataset/images/train/ID_PUwSfb.jpg
5071,ID_dZWfWh.jpg,cssvd,1.0,780.0,308.0,1758.0,2448.0,1,dataset/images/train/ID_dZWfWh.jpg,1,5071,"[308.0, 780.0, 2140.0, 978.0]",dataset/images/train/ID_dZWfWh.jpg

In [6]:
valid = pd.read_csv("dataset/Val_df.csv")

valid.sample(5)

,Image_ID,class,confidence,ymin,xmin,ymax,xmax,class_id,ImagePath
1916,ID_yMKmc2.jpeg,anthracnose,1.0,57.0,607.0,3024.0,2688.0,0,dataset/images/train/ID_yMKmc2.jpeg
1302,ID_qgcRFa.jpg,cssvd,1.0,794.0,10.0,1796.0,1398.0,1,dataset/images/train/ID_qgcRFa.jpg
240,ID_ASOu9k.jpg,healthy,1.0,0.0,84.0,310.0,480.0,2,dataset/images/train/ID_ASOu9k.jpg
1415,ID_Vn1626.jpg,cssvd,1.0,35.0,31.0,1280.0,820.0,1,dataset/images/train/ID_Vn1626.jpg
997,ID_ydI3Pa.jpg,anthracnose,1.0,516.0,613.0,2443.0,1563.0,0,dataset/images/train/ID_ydI3Pa.jpg

In [8]:
valid["category_id"] = valid["class"].map(category_ids)
valid["id"] = valid.index.values
valid["bbox"] = valid.apply(
	lambda x: [x["xmin"], x["ymin"], x["xmax"] - x["xmin"], x["ymax"] - x["ymin"]], axis=1
)
valid["image_id"] = valid["ImagePath"].values


valid.sample(5)

,Image_ID,class,confidence,ymin,xmin,ymax,xmax,class_id,ImagePath,category_id,id,bbox,image_id
893,ID_oRpSf2.jpeg,cssvd,1.0,997.0,99.0,2523.0,3919.0,1,dataset/images/train/ID_oRpSf2.jpeg,1,893,"[99.0, 997.0, 3820.0, 1526.0]",dataset/images/train/ID_oRpSf2.jpeg
707,ID_AYLNiX.jpeg,healthy,1.0,58.0,238.0,1264.0,559.0,2,dataset/images/train/ID_AYLNiX.jpeg,2,707,"[238.0, 58.0, 321.0, 1206.0]",dataset/images/train/ID_AYLNiX.jpeg
676,ID_VMJjCQ.jpg,anthracnose,1.0,1662.0,252.0,2048.0,1160.0,0,dataset/images/train/ID_VMJjCQ.jpg,0,676,"[252.0, 1662.0, 908.0, 386.0]",dataset/images/train/ID_VMJjCQ.jpg
1015,ID_wLwENy.jpg,anthracnose,1.0,182.0,106.0,1256.0,686.0,0,dataset/images/train/ID_wLwENy.jpg,0,1015,"[106.0, 182.0, 580.0, 1074.0]",dataset/images/train/ID_wLwENy.jpg
1851,ID_RhAKBi.jpeg,healthy,1.0,1335.0,2912.0,3024.0,4032.0,2,dataset/images/train/ID_RhAKBi.jpeg,2,1851,"[2912.0, 1335.0, 1120.0, 1689.0]",dataset/images/train/ID_RhAKBi.jpeg

In [9]:
columns = ["image_id", "bbox", "category_id", "id"]

train[columns].to_json(
	"dataset/train.json",
	# orient="records",
	# lines=True,
)
valid[columns].to_json(
	"dataset/valid.json",
	# orient="records",
	# lines=True,
)